### PR TITLE
Increase timeout to 50ms

### PR DESCRIPTION
**Pull request by xtuchyna**
## This introduces a breaking change

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by harshad16** [comment]
regate

**Comment by harshad16** [comment]
The zuul gate will not auto-merge till a reviewer with write access approvers this PR.

**Comment by harshad16** [comment]
@pacospace can you have a look at this PR, it feels fine can you approve it.
as till someone with write access doesn't approve this won't merge automatically.

**Comment by xtuchyna** [comment]
shouldnt we allow everybody from the AICoE team to have the write access to this project?

**Comment by harshad16** [comment]
I don't know if everyone should have write access, it could be a point to discuss. 
For now, you can go ahead and merge this PR.

**Pull request merged**
