### PR TITLE
Feature/preprocess storage

### PR DESCRIPTION
**Pull request by xtuchyna**
## This introduces a breaking change

- [x] Yes
- [ ] No

## Description
All of the processed information is now stored in srcopsmetrics/processed/ to each organization and repository respectively.

This PR includes
- major name refactor of the pre_processing class to processing class
The reason behind the name change is, that preprocessing refers more to outlier removal rathern than just extracting specific information from already stored knowledge
- Processing now fully uses class advantages (besides a few static methods)
- new decorator '@ProcessedKnowledge' available
this decorator is used in Processing to any method that is supposed to have its processed information stored either locally or remotelly.

### CODE REVIEW

**Comment by xtuchyna** [comment]
The question is, when it should *update* the processed knowledge. Right now it just checks if anything exisits in processed directory, if so it returns it. Should we add another parameter (e.g. -u ) or should it be part of the create knowledge process (-c) ?

**Comment by pacospace** [comment]
> The question is, when it should _update_ the processed knowledge? Right now it just checks if anything exisits in processed directory, if so it returns it. Should we add another parameter (e.g. -u ) or should it be part of the create knowledge process (-c) ?
> 
> resolves #96

See https://github.com/AICoE/SrcOpsMetrics/issues/96#issuecomment-618907682

**Comment by xtuchyna** [comment]
> Please rebase with master and have a look at [xtuchyna#2](https://github.com/xtuchyna/SrcOpsMetrics/pull/2). For the rest LGTM! Thanks beers

done!

**Comment by xtuchyna** [comment]
@pacospace I've just added that -c flag also removes previously processed storage

**Comment by xtuchyna** [comment]
@pacospace I've looked into that, and it is the case of analysing only the closed issues, not the open ones.

Specifically, the PR235 references Issue205. However, PR235 was rejected and Issue205 remained open, therefore we cannot reference currently active Issue205, because we did not analyse it.

This is part of the next PR that will soon come today, where I changed the analysis to also inspect currently active issues and pullrequests.

**Comment by pacospace** [comment]
> @pacospace I've looked into that, and it is the case of analysing only the closed issues, not the open ones.
> 
> Specifically, the PR235 references Issue205. However, PR235 was rejected and Issue205 remained open, therefore we cannot reference currently active Issue205, because we did not analyse it.
> 
> This is part of the next PR that will soon come today, where I changed the analysis to also inspect currently active issues and pullrequests.

so do you want this PR to be merged even if does not work entirely? and you address the issue in another PR?

**Comment by xtuchyna** [comment]
@pacospace issue is addressed in another PR, therefore I want this PR to be merged

**Pull request merged**
